version: '3.4'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - 3308:3308
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: contestgenerator
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
      MYSQL_TCP_PORT: 3308
    restart: always
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  contestgenerator:
    image: yungd1plomat/contestgenerator
    environment:
      - CONNECTION_STRING=Server=mysql;Port=3308;Database=contestgenerator;Uid=dbuser;Pwd=dbuserpassword;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    build:
      context: .
      dockerfile: ContestGenerator/Dockerfile
    depends_on:
      - mysql
      - caddy
    ports:
      - 5000:5000
    restart: always

volumes:
  mysqldb:
  caddy_data:
  caddy_config:

