version: '3.4'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - localnetwork
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: contestgenerator
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
      MYSQL_TCP_PORT: 3308
    restart: always
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
      - localnetwork
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  contestgenerator:
    image: yungd1plomat/contestgenerator
    container_name: contestgenerator
    environment:
      - CONNECTION_STRING=Server=mysql;Port=3308;Database=contestgenerator;Uid=dbuser;Pwd=dbuserpassword;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;
    build:
      context: .
      dockerfile: ContestGenerator/Dockerfile
    networks:
      - localnetwork
    depends_on:
      - mysql
      - caddy
    restart: always

networks:
  caddy:
    external: true
  localnetwork:
    external: false
    
volumes:
  mysqldb:
  caddy_data:
  caddy_config: