version: '3.4'
services:
  pg:
    image: postgres
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - localnetwork
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuserpassword
      - POSTGRES_DB=contestgenerator
    restart: always
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
      - localnetwork
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  contestgenerator:
    image: yungd1plomat/contestgenerator
    container_name: contestgenerator
    environment:
      - CONNECTION_STRING=Host=pg;Port=5432;Database=contestgenerator;Username=dbuser;Password=dbuserpassword;Timeout=180;CommandTimeout=180;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;
      - ADMIN_PASS=Admin_12345
    build:
      context: .
      dockerfile: ContestGenerator/Dockerfile
    networks:
      - localnetwork
    depends_on:
      - pg
      - caddy
    restart: always

networks:
  caddy:
    external: true
  localnetwork:
    external: false
    
volumes:
  db:
  caddy_data:
  caddy_config: